# Generated by Django 2.0.3 on 2019-10-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=200)),
                ('created', models.DateTimeField(verbose_name='date created')),
                ('conversation_id', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
    ]
